name: diffr_attk
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.0.5=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - ca-certificates=2022.12.7=ha878542_0
  - certifi=2022.12.7=pyhd8ed1ab_0
  - debugpy=1.5.1=py39h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - entrypoints=0.4=py39h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - ipykernel=6.15.2=py39h06a4308_0
  - ipython=8.7.0=py39h06a4308_0
  - jedi=0.18.1=py39h06a4308_1
  - jq=1.6=h36c2ea0_1000
  - jupyter_client=7.4.7=py39h06a4308_0
  - jupyter_core=4.11.2=py39h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - matplotlib-inline=0.1.6=py39h06a4308_0
  - ncurses=6.3=h5eee18b_3
  - nest-asyncio=1.5.5=py39h06a4308_0
  - oniguruma=6.9.7.1=h27cfd23_0
  - openssl=1.1.1s=h7f8727e_0
  - packaging=21.3=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=22.3.1=py39h06a4308_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyparsing=3.0.9=py39h06a4308_0
  - python=3.9.15=h7a1cb2a_2
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pyzmq=23.2.0=py39h6a678d5_0
  - readline=8.2=h5eee18b_0
  - setuptools=65.5.0=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.40.0=h5082296_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tk=8.6.12=h1ccaba5_0
  - tornado=6.2=py39h5eee18b_0
  - traitlets=5.7.1=py39h06a4308_0
  - tzdata=2022g=h04d1e81_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.8=h5eee18b_0
  - zeromq=4.3.4=h2531618_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - absl-py==1.3.0
    - antlr4-python3-runtime==4.9.3
    - anyio==3.6.2
    - appdirs==1.4.4
    - black==22.3.0
    - cachetools==5.2.0
    - charset-normalizer==2.1.1
    - click==8.1.3
    - cloudpickle==2.2.0
    - contourpy==1.0.6
    - cox==0.1.post3
    - cycler==0.11.0
    - dill==0.3.6
    - drjit==0.3.2
    - fairscale==0.4.12
    - fastapi==0.89.1
    - filelock==3.8.0
    - fonttools==4.38.0
    - future==0.18.2
    - fvcore==0.1.5.post20221122
    - gitdb==4.0.10
    - gitpython==3.1.29
    - google-auth==2.14.1
    - google-auth-oauthlib==0.4.6
    - grpcio==1.50.0
    - h11==0.14.0
    - huggingface-hub==0.11.0
    - hydra-core==1.3.1
    - idna==3.4
    - importlib-metadata==5.1.0
    - iopath==0.1.9
    - ipywidgets==8.0.3
    - jupyterlab-widgets==3.0.4
    - kiwisolver==1.4.4
    - line-profiler==4.0.2
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.6.2
    - mitsuba==3.1.1
    - mypy-extensions==0.4.3
    - numpy==1.23.5
    - oauthlib==3.2.2
    - omegaconf==2.2.3
    - opencv-python==4.6.0.66
    - pandas==1.5.2
    - pathspec==0.10.2
    - pillow==9.3.0
    - platformdirs==2.5.4
    - portalocker==2.6.0
    - protobuf==3.20.3
    - psutil==5.9.4
    - py3nvml==0.2.7
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycocotools==2.0.6
    - pydantic==1.10.4
    - pydot==1.4.2
    - pytz==2022.7
    - pyyaml==6.0
    - regex==2022.10.31
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - smmap==5.0.0
    - sniffio==1.3.0
    - starlette==0.22.0
    - tabulate==0.9.0
    - tensorboard==2.11.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - termcolor==2.1.1
    - timm==0.6.12
    - toml==0.10.2
    - tomli==2.0.1
    - torch==1.10.0+cu111
    - torchvision==0.11.0+cu111
    - torchaudio==0.10.0
    - tqdm==4.64.1
    - typing-extensions==4.4.0
    - urllib3==1.26.13
    - uvicorn==0.20.0
    - werkzeug==2.2.2
    - widgetsnbextension==4.0.4
    - xmltodict==0.13.0
    - yacs==0.1.8
    - zipp==3.11.0
